In [2]:
import numpy as np

In [8]:
a= np.array([2,3,4,8,9,'numpy'])
print(a.dtype)
print(a)

<U11
['2' '3' '4' '8' '9' 'numpy']


In [7]:
b=np.array(range(1,11))

In [5]:
l=[1,2,3]
l1 = np.array(l)
print(l)
print(l1)

[1, 2, 3]
[1 2 3]


In [10]:
print(np.arange(1020,1.2))
print(np.arange(10))

[]
[0 1 2 3 4 5 6 7 8 9]


In [3]:
print(np.linspace(10,100,5))

[ 10.   32.5  55.   77.5 100. ]


In [15]:
a = np.zeros((3,3),np.int)

print(a)
a.shape

[[0 0 0]
 [0 0 0]
 [0 0 0]]


(3, 3)

In [16]:
a = np.ones((3,3),np.int)

print(a)
a.shape

[[1 1 1]
 [1 1 1]
 [1 1 1]]


(3, 3)

In [28]:
c = np.random.randint(10)
print(c)

6


In [29]:
c = np.random.randint(10,100,6)
print(c)
print(c.ndim)
print(c.shape)
print(c.itemsize) # no of bits

[55 60 62 98 74 20]
1
(6,)
4


In [30]:
c = np.random.randint(10,100,(2,3))
print(c)
print(c.ndim)
print(c.shape)
print(c.itemsize) # no of bits

[[84 94 97]
 [57 34 84]]
2
(2, 3)
4


In [25]:
c = np.random.randint(10,100,(2,3,4))
print(c)
print(c.ndim)
print(c.shape)
print(c.itemsize) # no of bits

[[[44 51 49 34]
  [82 47 20 94]
  [28 62 83 18]]

 [[31 71 22 91]
  [70 30 85 81]
  [14 46 31 15]]]
3
(2, 3, 4)
4


In [41]:
c = np.random.randint(5,10,(2,3,4))
print(c)
print(c.ndim)
print(c.shape)
print(c.itemsize) # no of bits

[[[7 5 6 6]
  [6 6 6 7]
  [7 9 8 6]]

 [[7 6 7 5]
  [9 9 9 8]
  [6 5 6 5]]]
3
(2, 3, 4)
4


In [38]:
# generates random values between 0 and 1 of specified size m1xm2x.....
d1 = np.random.rand(2,3)
print(d1)
print('__________________________________')
d2 = np.random.random((2,3))
print(d2)

[[0.6231633  0.55359745 0.03739018]
 [0.56419445 0.77234723 0.40899425]]
__________________________________
[[0.52970399 0.195819   0.28883252]
 [0.94526377 0.35299865 0.9782364 ]]


In [50]:
# indexing
a = np.arange(25)
print(a)
print(a[:4])
print(a[:-4])
print(a[-4:])
print(a[len(a)//2])
print(a[len(a)//2:])
print(a[:len(a)//2])
print(a[[0,3,5]])
print(a[1:10:2])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[0 1 2 3]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[21 22 23 24]
12
[12 13 14 15 16 17 18 19 20 21 22 23 24]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[0 3 5]
[1 3 5 7 9]


In [52]:
a1 = np.arange(25).reshape(25,1)
print(a1)

a2 = np.arange(25).reshape(1,25)
print(a2)

a3 = np.arange(25).reshape(5,5)
print(a3)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [71]:
a4 = np.arange(9).reshape(3,3)
print(a4)
print(a4[:])
print(a4[0]) # first row
print(a4[1]) # second row
print(a4[2]) # thrid row
print(a4[1:]) # two and three rows
print(a4[2:]) # only third row
print(a4[0,]) # first row
print(a4[1,]) # second row
print(a4[2,]) # thrid row


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]
[3 4 5]
[6 7 8]
[[3 4 5]
 [6 7 8]]
[[6 7 8]]
[0 1 2]
[3 4 5]
[6 7 8]
[[0 1 2]]


In [74]:
print(a4[:,0]) # first col 
print(a4[:,1]) # second col
print(a4[:,2]) # third col

[0 3 6]


In [76]:
print(a4[:,[0,1]]) # first,second col 
print(a4[:,[1,0]]) # second,first col
print(a4[:,[2,0]]) # third, first col

[[0 1]
 [3 4]
 [6 7]]
[[1 0]
 [4 3]
 [7 6]]
[[2 0]
 [5 3]
 [8 6]]


In [77]:
print(a4[:1,[0,1]]) # first row ,and one, second col 

[[0 1]]


In [78]:
print(a4[::-1,::-1]) # reverse


[[8 7 6]
 [5 4 3]
 [2 1 0]]
